### ISSUE TITLE
Is aminal embed-able?

### ISSUE THREAD

**Issue by MichaelHipp** [liamg/darktile#118]
**Is your feature request related to a problem? Please describe.**
Is aminal intended to be embed-able? (This is being asked in the same sense that 3rd-party browsers can embed the Chrome web renderer.)

**Describe the solution you'd like**
I would like to be able to write a term emulator application with a particular UI which uses aminal as its embedded emulator to do the heavy lifting. The application would mostly implement a UI with a certain feature set and wrapped around aminal. 

**Describe alternatives you've considered**
It appears https://github.com/napsy/go-vte might be a possibility.

**Additional context**
I would like to build something equivalent to MobaXterm (avail only on Windows) for Linux. MobaXterm is the best terminal emulator I've ever used. Since switching to Linux it's about the only thing I miss from Windows. But it seems to have no equivalent on Linux (tho Remmina comes close). If I write something, I'd prefer it was in Go. ![feature-terminal](https://user-images.githubusercontent.com/99330/50375501-dca3e180-05c3-11e9-9058-f8423cd91357.png)

**Comment by liamg** [comment]
We're not too far from being able to do this, and it's definitely something I'd like for the future.

For now the focus is on windows support, `vttest` and some UI niceties, but we'll get there.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
