### ISSUE TITLE
Integrate Mosh support to get effortless user experience

### ISSUE THREAD

**Issue by maxhora** [liamg/darktile#128]
The issue to track investigation progress of getting mosh natively to Windows and use it from Aminal.exe

[update:15.02.19:MaxRis] As suggested by Alex, Aminal user should get mosh experience as simple as launching aminal by typing: `animal -shell mosh`.

**Comment by nikitar020** [comment]
> I've made several commits to https://github.com/nikitar020/mosh/tree/run-on-windows repository which add ability to run `mosh-client` on Windows, and also committed a ZIP file with `mosh-client.exe` (with minimal dependencies) extracted from `MSys2`. On Windows, the mosh wrapper expects those files to be in the same directory. So, when packaging Aminal for Windows we can include in the package:
> 1. `mosh` executable compiled from that branch: https://github.com/nikitar020/mosh/tree/run-on-windows
> 2. contents of the `mosh-client.zip` file from the same

Also see the issue  https://github.com/liamg/aminal/issues/166

**Comment by MaxRis** [comment]
@nikitar020 thank you for your efforts to find working Windows mosh solution. I'm updating this Issue to address next step challenges of Aminal and mosh integration. It would be nice to discuss possible approaches of integration.

**Comment by nikitar020** [comment]
> Aminal user should get mosh experience as simple as launching aminal by typing: `animal -shell mosh`.

I tested and this seems working on Windows, but the user will need to specify parameters as well:
```
aminal.exe -shell "mosh.exe -l username host-address.com"
```

On Linux this does not work but probably can be implemented by changing `platform/unixpty.go` file.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
