### ISSUE TITLE
OpenGL memory leak when minimizing/restoring window

### ISSUE THREAD

**Issue by maxhora** [liamg/darktile#129]
**Describe the bug**
It looks like OpenGL memory is leaking when the Aminal' window is restoring from minimized state.

**To Reproduce**
1. Run Aminal
2. Run Task Manager and note current Aminal memory usage
3. Try to minimize and restore the window several times
4. On each restoration of the window, the memory consumption increases by 4 to 6 MB.

**Expected behavior**
There should be no increase in memory usage when minimizing/restoring the Aminal's window.

**Environment (please complete the following information):**
 - OS + Version: `Windows`

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
