### ISSUE TITLE
Memory leaks on Window resizing

### ISSUE THREAD

**Issue by maxhora** [liamg/darktile#130]
**Describe the bug**
Amount if used RAM is slightly get increased if to keep to resize the window constantly.

**To Reproduce**
1. Run aminal and appropriate process monitor software.
2. Resize aminal's window constantly
3. Amount of used memory will constantly grow up 

**Environment (please complete the following information):**
 - OS + Version: Windows 10 1809
 - Shell: cmd.exe

Might be related to context of https://github.com/liamg/aminal/issues/129

**Comment by nikitar020** [comment]
Finally I made a PR https://github.com/liamg/aminal/pull/148, but did not manage to reliably determine the cause of the growth in memory usage. The Go's built-in memory diagnostics, such as `pprof` and `set GODEBUG=gctrace=1` do not show any growth in memory controlled by the Go runtime, so I'm deciding that all those memory is consumed by OpenGL. 
Under some conditions, Aminal can eat up even more than 1GB of RAM on my machine while the heap size reported by the GC does not grow above 30MB. (However, the amount of memory seems strictly depending on the window dimensions and tends to shrink down when the window gets smaller). I'm not an expert in OpenGL but I'm almost confident that the root of such a large memory consumption is the way OpenGL is used in Aminal - in particular, I'm suspecting that `OpenGLRenderer` (in `gui/renderer.go`) can be reimplemented in a more optimized way.

So I need advice on how to reimplement `OpenGLRenderer` and if that worth at all on current stage.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
