### ISSUE TITLE
Determine why Sixel VT escape sequences are not being processed on Windows

### ISSUE THREAD

**Issue by maxhora** [liamg/darktile#131]
**Describe the bug**
The windows build is either not receiving Sixel VT escape sequences properly or is not able to properly interpret them. (this may apply to other escape sequences as well)

**To Reproduce**
1. Start aminal.exe on windows (currently requires the shell to be specified by cli parameter `aminal --shell cmd.exe`)
2. Output the contents of example.sixel to the tty `type example.sixel`

**Expected behavior**
The test image should display in the terminal window.

**Observed behavior**
A large quantity of text is displayed in the terminal window.

**Screenshots**
![image](https://user-images.githubusercontent.com/42252263/49665283-6ed3b380-fa22-11e8-925c-9e8c208a3fa7.png)
![image](https://user-images.githubusercontent.com/42252263/49665352-9c206180-fa22-11e8-934d-8ae81564e966.png)

**Environment:**
 - Windows 10 v.1809

**Additional context**

**Logs**
I'm not currently able to capture a debug log on windows due to what seems to be a misbehavior in the operating system when combining output pipes and ConPTY API hosts (I get the output from the guest processes but not the host).

**Comment by MaxRis** [comment]
already merged changes targeting this issue to add sixel support on Windows:
https://github.com/liamg/aminal/pull/132
https://github.com/jumptrading/aminal/pull/13

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
