### ISSUE TITLE
Support hyperlinks like in gnome-terminal + iTerm2

### ISSUE THREAD

**Issue by damageboy** [liamg/darktile#147]
I'd like aminal to be compatible with iTerm2 / gnome-terminal vis-a-vis extended hyperlink support

GNOME Terminal (VTE) and iTerm2 have implemented this feature: hyperlinks (HTML-like anchors).

This is different from the autodetection of URLs that appear onscreen. This time the text that appears does not have to look like a URL, it can be anything, and the target URL is specified explicitly by the utility along with the displayed text, using the OSC 8 escape sequence.

For further information on this feature, see
    A dedicated page with all the details: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda
    GNOME Terminal bugreport (way too long and probably not that interesting at this point, although might contain some useful tips): https://bugzilla.gnome.org/show_bug.cgi?id=779734
    iTerm2 bugreport: https://gitlab.com/gnachman/iterm2/issues/5158

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
