### ISSUE TITLE
Auto-update functionality

### ISSUE THREAD

**Issue by maxhora** [liamg/darktile#151]
**Is your feature request related to a problem? Please describe.**
It's required to take extra actions to update application to the latest available version (check GitHub Releases page, download new binary and replace old one).

**Describe the solution you'd like**
Automated way to detect and notify about available update, new binaries download and replacement of old files, launch updated app.

**Describe alternatives you've considered**
- Omaha ( https://github.com/google/omaha )
- Custom implementation to check new GitHub Releases availability

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
