### ISSUE TITLE
Log is spammed with OpenGL warning

### ISSUE THREAD

**Issue by vadymeng0** [liamg/darktile#154]
**Describe the bug**
When run with `-debug` option on Linux, the Aminal's log is spammed with the following message:
```
2019-01-16T21:56:21.323+0700    INFO    gui/gui.go:531  GL debug message: using glBufferSubData(buffer 177, offset 0, size 96) to update a GL_STATIC_DRAW buffer
```

**To Reproduce**
1. Run Aminal with `-debug` option
2. The log will start filling with the above message 
3. It seems that more messages inserted when moving the mouse

**Expected behavior**
Normally the should be no OpenGL messages

**Environment (please complete the following information):**
 - OS `Debian GNU/Linux 9 (stretch)`

**Additional context**
1. There is no such a problem on Windows.
2. Displaying OpenGL debug messages when running with `-debug` option has been added by PR https://github.com/liamg/aminal/pull/148

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
