### ISSUE TITLE
Update Travis to create GitHub Release with additional zip package of mosh-client executables and Aminal.exe

### ISSUE THREAD

**Issue by vadymeng0** [liamg/darktile#166]
**Is your feature request related to a problem? Please describe.**
There is no "official" `mosh-client` for Windows, so we need to include own one. The problem is that the original implementation uses `mosh` wrapper which is written in Perl, and including the whole Perl distribution with Aminal is not desirable.

**Describe the solution you'd like**
1. I found a `mosh` wrapper written in Go, and made it working on Windows: https://github.com/nikitar020/mosh/tree/run-on-windows. We could include that wrapper in the Aminal distribution package on Windows.
2. I extracted the `mosh-client` executable with its dependencies and put them in the same repository as `mosh-client.zip` file. Those files should be included in the distribution package as well, and installed in the same directory as `aminal.exe` file.

[update:15.02.19:MaxRis] Lets try to put all mosh related Windows binaries into the Aminal's repo and update Travis ci to build additional .zip package with latest Aminal.exe and mosh executables.

**Comment by MaxRis** [comment]
Please check bottom ([update:15.02.19:MaxRis] section) of the Issue description to get idea of what should be done to resolve this Issue.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
