### ISSUE TITLE
Refine and polish text selection functionality

### ISSUE THREAD

**Issue by maxhora** [liamg/darktile#170]
There are multiple different kind of issues, glitches or good to support functionality:

- Double click should select whole word, triple click should select whole line, any further dragging extends available selection accordingly (e.g. how putty works). In case of triple click and dragging - selection gets extended to whole lines.
- Selection and dragging up or down outside of the screen should trigger scrolling and selection of buffer content.

**Comment by nikitar020** [comment]
At least one issue has been fixed: https://github.com/liamg/aminal/pull/172

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
