### ISSUE TITLE
please make sure rectangular select & copy is implemented

### ISSUE THREAD

**Issue by cjw296** [liamg/darktile#217]
**Is your feature request related to a problem? Please describe.**

I often need to select rectangular areas out of shell content and copy them elsewhere.
Normal line-based select doesn't work for this.

**Describe the solution you'd like**

Rectangular selection like you get in macOs Terminal with Alt+drag'n'select

**Describe alternatives you've considered**

There aren't any really.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
