### ISSUE TITLE
Build Aminal binaries for opened PRs

### ISSUE THREAD

**Issue by maxhora** [liamg/darktile#224]
**Is your feature request related to a problem? Please describe.**
To simplify verification of changes in PR it makes sense to build binaries per PR and, for example, publish links to binaries as comment at the PR page.

**Describe the solution you'd like**
Update Travis CI job to publish PR builds to some external cloud storage provider (like S3 bucket) and comment PR page with link to built packages.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
