### ISSUE TITLE
Error parsing X10 mouse sequences

### ISSUE THREAD

**Issue by klamonte** [liamg/darktile#234]
Using today's git head build, testing with [Jexer](https://gitlab.com/klamonte/jexer) , ran across this error message:

 error   terminal/output.go:117  Error handling escape sequence: Unknown CSI control sequence: 0x6C (ESC[?1002;1003;1005;1006h)

Jexer sends these sequences to do the following:
* Ps = 1 0 0 2  -> Use Cell Motion Mouse Tracking, xterm.
* Ps = 1 0 0 3  -> Use All Motion Mouse Tracking, xterm.
* Ps = 1 0 0 5  -> Enable UTF-8 Mouse Mode, xterm.
* Ps = 1 0 0 6  -> Enable SGR Mouse Mode, xterm.

The desired effect is to receive all mouse events in SGR encoding, with graceful fallback to button events and/or UTF-8 encoding.

On exit, Jexer disables these options in reverse order, so another error in the log is shown.

**Describe the bug**
Actual behavior is no mouse events, not even button presses.

**To Reproduce**
Download latest Jexer, 'ant build', 'java -jar build/jar/jexer.jar'.

**Expected behavior**
Expected (xterm) behavior is all mouse events with SGR encoding, or:
* If SGR encoding is unsupported, UTF-8 encoding.
* If all mouse events are unsupported, button and button+motion events.

**Environment (please complete the following information):**
Fedora 28
Go go1.10.3 gccgo (GCC) 8.2.1 20181215
bash

**Additional context**
I am hoping that another terminal capable of running Jexer with sixel support emerges, this one looks pretty promising.

Jexer also uses a Privacy Message (ESC ^ {stuff} ESC \) to tell itself that it is running inside itself, so don't draw the mouse pointer.  Looks like aminal is missing both the PM (ESC ^) and the ST (ESC \), and not discarding what is in between them.

**Comment by rrrooommmaaa** [comment]
@klamonte Hi Kevin. Can you check `roman4` branch (PR https://github.com/liamg/aminal/pull/233)?
It has button-motion (?1002) and SGR encoding (?1006) support. Would thatsuit your needs? Is it ok that only left-button motion is supported? Private messaging will be supported on a different branch.

**Comment by klamonte** [comment]
@rrrooommmaaa The roman4 branch does provide some mouse support, enough to click on menu items and drag windows around, making Jexer usable.  Thank you!

Side question: Is there a way to change the font?

**Comment by rrrooommmaaa** [comment]
@klamonte Hmm... Looks like the font is hard-coded in gui/fonts.go

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
