### ISSUE TITLE
Overwriting sixel image data with text cells leaves artifacts

### ISSUE THREAD

**Issue by klamonte** [liamg/darktile#237]
**Describe the bug**
[Jexer](https://gitlab.com/klamonte/jexer) uses a mix of sixel and text on screen, to provide draggable windows containing images.  When using sixel in aminal, overwriting the cells with text leaves sixel pixels where the text background should be. and it also looks like aminal scrolls the screen when it shouldn't.

Easier to see than say, see below.

**To Reproduce**
1. Run Jexer: 'java -jar /path/to/jexer.jar'
2. Alt-F to open menu, then Left to switch to hamburger menu, then Open Image...
3. Pick an image file from the dialog box.
4. Drag window around.

**Expected behavior**
This is the screen under xterm, first when the image is loaded and then dragged:

![xterm_sixel1](https://user-images.githubusercontent.com/4357501/53411078-2ecdfe00-398b-11e9-8e36-0584bce979d1.png)

![xterm_sixel2](https://user-images.githubusercontent.com/4357501/53411085-3392b200-398b-11e9-9bb5-08049fc5ba1e.png)

**Screenshots**
This is the screen under aminal, first when the image is loaded and then dragged:

![aminal_sixel1](https://user-images.githubusercontent.com/4357501/53411105-3e4d4700-398b-11e9-858d-0b7d7217d707.png)

![aminal_sixel2](https://user-images.githubusercontent.com/4357501/53411112-4311fb00-398b-11e9-8ad6-c835ab0a2ff4.png)

**Environment (please complete the following information):**
 - Fedora 29
 - Go version go1.10.3 gccgo
 - bash

**Comment by klamonte** [comment]
Looking at the aminal screenshots, it also appears that aminal is not responding to Jexer's "CSI 14 t" sequence, which is supposed to return the screen size in pixels.  That is probably why the scrolling is happening: Jexer assumes a screen size of 640x400 to figure out the text cell dimensions.  Without the real text cell dimensions, Jexer is drawing all the text elements, and then going outside the border of its window when it draws the sixel.

So don't worry about the scrolling effect, that may be fine.  But one should be able to overwrite sixel pixels with text data including background color, that's the real issue here.

**Comment by klamonte** [comment]
I now have session captures ready-made ways to test this at: https://jexer.sourceforge.io/sixel.html

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
