### ISSUE TITLE
Do not create newlines in long lines when copying

### ISSUE THREAD

**Issue by daviesalex** [liamg/darktile#249]
**Describe the bug**
Aminal inserts newlines in all copied data, even when there are none

**To Reproduce**
1. Create a multi line file (e.g. SSH public key)
2. Read it in the terminal (e.g. via cat)
3. Select it so it copies
4. Paste it into a different editor (e.g. sublime)
5. Notice that it has inserted newlines into the long line

**Expected behavior**
No newlines added.

Putty gets this right if you do the exact same process.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
