### ISSUE TITLE
UTF8 mouse encoding support (?1005)

### ISSUE THREAD

**Issue by rrrooommmaaa** [liamg/darktile#268]
Some of the programs use UTF8 mouse encoding. This is not urgent as we already have SGR implemented (which supercedes UTF8)

Setting/unsetting ?1005 mode would affect the format of mouse event sequences sent from `aminal` to application.
Details: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html (Extended coordinates section)

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
