### ISSUE TITLE
Add Any-Event mouse tracking support

### ISSUE THREAD

**Issue by rrrooommmaaa** [liamg/darktile#269]
Any-event mode is the same as button-event mode, except that all motion
events are reported, even if no mouse button is down.  It is enabled by
specifying setting ?1003 mode.

**Describe the solution you'd like**
Do whatever `xterm` does.

**Describe alternatives you've considered**
Currently, button-event mode is supported which is sufficient for most applications.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
