### ISSUE TITLE
[Question] How do I select a font?

### ISSUE THREAD

**Issue by pinpox** [liamg/darktile#272]
There is no setting in the configuration example to set the font to be used.
How do I set it to a font I like? Also are bitmap fonts supported (e.g. terminus font)?

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!

**Comment by pinpox** [comment]
> Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!

Is there any info on the rewrite? Cool to see progress on this project!

**Comment by liamg** [comment]
Hey @pinpox - nothing more than is in the readme at the moment, but I'd like to invest some more time on it now. What sort of thing did you have in mind? I can put a blog post or something together if there is any interest.

**Comment by pinpox** [comment]
> I can put a blog post or something together if there is any interest.

Would like to read that! I'm just generally interested in the motivation and state of the project as well as a roadmap on  what the plans are and where it's going. Have a great day!
