### ISSUE TITLE
tmux like replacement

### ISSUE THREAD

**Issue by ghost** [liamg/darktile#275]
This is a smart approach. Virtualise all the cross platform OS terminal issues by using an opengl canvas !

Would this allow me to program it to have many tiling windows etc.
Basically what tmux does.
Then i can load up a daemon into each view and see the logs streaming through for each daemon.
Or can i also use REPL also to control the daemons respectively.

Hope i am explaining myself ...

**Comment by Seirdy** [comment]
What's the advantage of duplicating tmux/window-manager features over using tmux normally?

**Comment by test-account-0** [comment]
There is no need to reimplement tmux. There is - tmux -CC

https://github.com/tmux/tmux/wiki/Control-Mode

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
