### ISSUE TITLE
terminal error

### ISSUE THREAD

**Issue by nxsre** [liamg/darktile#277]
1.555757467773259e+09	error	terminal/output.go:117	Error handling escape sequence: Unknown OSC control sequence: 1;../liamg/aminal
github.com/liamg/aminal/terminal.(*Terminal).processInput
	/tmp/.gobuild/src/github.com/liamg/aminal/terminal/output.go:117

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
