### ISSUE TITLE
Support iTerm2 Proprietary Escape Codes

### ISSUE THREAD

**Issue by galvinben** [liamg/darktile#28]
**Describe the bug**
On running aminal, i recieve the following error:

```
1.540306868124171e+09   error   terminal/output.go:96   Error handling escape sequence: Unknown OSC control sequence: 1;../liamg/aminal
github.com/liamg/aminal/terminal.(*Terminal).processInput
```

**To Reproduce**
1. run `./aminal`
2. See error

**Expected behavior**
There should be no errors on running

**Environment (please complete the following information):**
 - macOS Mojave 10.14
 - go version go1.11 darwin/amd64

**Comment by liamg** [comment]
What version of zsh are you using? I can't reproduce with `zsh 5.3 (x86_64-apple-darwin17.0)`

**Comment by jamesnetherton** [comment]
I see the same error with `zsh 5.3.1 (x86_64-debian-linux-gnu)`. If I stop sourcing `oh-my-zsh` in my `.zshrc`, the error goes away.

**Comment by jcarter3** [comment]
I get the same error with `zsh 5.6.2 (x86_64-apple-darwin17.7.0)`

**Comment by mikechernev** [comment]
Could this be related to the oh-my-zsh or its themes?
I get the error as well, although I don't see any impact on the functionality or the performance.

`macOS High Sierra (10.13.6)`
`zsh 5.3 (x86_64-apple-darwin17.0)`

**Comment by liamg** [comment]
Yeah, it's sending an OSC code that I can't find documented anywhere. It's not a major issue, but I'd like to find out what oh-my-zsh is trying to do and whether we can support it.

**Comment by liamg** [comment]
Looks at the oh-my-zsh source, it looks like it's trying to add functionality for custom iterm2 escape codes, which I guess I'll have to either ignore or support. I haven't gone though the details yet, but it's basically [this stuff](https://iterm2.com/documentation-escape-codes.html).

**Comment by beaugunderson** [comment]
i got [a ton of these](https://gist.github.com/beaugunderson/a8f3231e20b3b0b03880b9f5abb2c92a) (and no screen output) the first time I launched as well
