### ISSUE TITLE
Poor performance on Windows

### ISSUE THREAD

**Issue by lietu** [liamg/darktile#280]
**Describe the bug**
It seems `aminal` has pretty awful performance compared to other options out there.

I saw someone else had tried a bunch of terminal emulators, benchmarking them simply by taking the `.txt` representation of the RFC 3261 (http://www.ietf.org/rfc/rfc3261.txt approx. 15k lines) and dumping the file contents on the screen, so I decided to try the same.

On `cmd.exe` I used the `timeit` command from https://www.microsoft.com/en-us/download/details.aspx?id=17657 as per https://stackoverflow.com/a/752307/3989287 to get execution time. On `bash` under Windows Subsystem for Linux I used the `time` command.

 - For `cmd.exe` I specifically executed: `timeit cmd /c type rfc3261.txt`
 - For `bash` on WSL I specifically executed: `time cat rfc3261.txt`

It typically seems that most time is always spent on the first run, likely due to them growing the buffer to the maximum size before becoming more performant, so I ran every test 3 times in a row in the same terminal without reopening it and recorded the range rounded to two decimals.

I compared:

 - `conhost` (the Windows default command prompt)
 - [Alacritty](https://github.com/jwilm/alacritty) 0.3.0
 - [Aminal](https://github.com/liamg/aminal/releases/tag/Nightly-develop-2019-04-22-8f0027d) 2019-04-22 8f0027d
 - [ConEmu](https://conemu.github.io/) 161206 x64
 - [Hyper](https://hyper.is/) 2.1.2

I set each console window to be 128x48 characters in size. I've configured ConEmu to use DejaVu Sans Monospace -font but the others are using whatever is their default.

I believe these were the defaults, but just in case: 

 - `Alacritty` had 10000 line buffer
 - `aminal` I believe defaults to 1000 line buffer
 - `ConEmu` had 10000 line buffer
 - `conhost` had 9001 line buffer
 - `Hyper` had 1000 line buffer

**The results I got**

`cmd.exe`:

 - `Alacritty`: 1.15 - 1.28s
 - `aminal`: 136.81 - 156.31s (2min 16.81s - 2min 36.31s)
 - `ConEmu`: 1.63 - 2.08s
 - `conhost`: 0.90 - 2.95s
 - `Hyper`: 1.14 - 1.30s

`bash`:

 - `Alacritty`: 1.20 - 1.50s
 - `aminal`: 126.61 - 147.89s (2m 6.61s - 2m 27.89s)
 - `ConEmu`: 0.79 - 1.75s
 - `conhost`: 0.94 - 4.13s
 - `Hyper`: 1.19 - 1.46s

The absolute values I got are less relevant (especially because of configuration differences), but the point is the relative difference of everything else being measured in seconds and `aminal` being consistently incredibly slow compared to any other alternative. It seems `aminal` was 35.8x to 134.7x slower than `conhost` (with `bash`, the `cmd.exe` differences fall in the ~75-85x range).

**To Reproduce**
1. Download http://www.ietf.org/rfc/rfc3261.txt
2. Launch `aminal`
3. (Optional) Start `bash`
4. Dump the contents of `rfc3261.txt` into the terminal with `type` or `cat`

**Expected behavior**
Printing out the file contents should take a time measured in seconds, not minutes.

**Environment (please complete the following information):**
 - Windows (Win10 1809) 
 - Aminal 2019-04-22 (8f0027d)
 - `cmd.exe` & WSL `bash`

**Additional context**
As additional notes `aminal` was the only one to keep an additional host terminal window open, was the most difficult to size to the desired size, and was the only one with issues with the clipboard (pasting multiple lines of text ended up with extra blank lines in between the lines).

![image](https://user-images.githubusercontent.com/1296558/56924505-bba14f00-6ad5-11e9-9961-1ac5d7f09630.png)

I realize this is software in development and so on, but thought I'd mention these as well.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
