### ISSUE TITLE
Poor performance on macos with VIM

### ISSUE THREAD

**Issue by chichid** [liamg/darktile#283]
**Describe the bug**
The latency is pretty high when using VIM.

**To Reproduce**
1. Got the terminal through brew
2. Run the command "aminal"
3. Try to edit a file with VIM

**Expected behavior**
It should be as smooth or smoother than the mac built-in terminal  

**Screenshots**
May add an animated gif if necessary, but this is pretty straight forward to reproduce.

**Environment (please complete the following information):**
 - OS + Version: 
![image](https://user-images.githubusercontent.com/6054451/63030165-e1cddd80-be7f-11e9-9cbe-43892987217e.png)

 - Go Version [e.g. 1.10.1] - go version go1.12.8 darwin/amd64

 - Shell [e.g. Bash/Zsh] - bash

**Additional context**

**Logs**

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
