### ISSUE TITLE
panic: to deterimin current monitor the window must be set

### ISSUE THREAD

**Issue by Merith-TK** [liamg/darktile#286]
**Describe the bug**
The program crashes with the panic error in the title
https://i.imgur.com/NaQtYRw.png

**To Reproduce**
1. use `go get` to install on archlinux
2. launch the program in a terminal 

**Expected behavior**
Some GUI to open, even if broken

**Screenshots**

**Environment (please complete the following information):**
 - OS + Version: Archlinux
 - Go Version: 1.13.6 linux/amd64
 - Shell: Bash

**Additional context**
https://i.imgur.com/NaQtYRw.png

**Logs**
https://i.imgur.com/B9tiye1.png

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
