### ISSUE TITLE
Not intended behaviour when using go exec.Command()

### ISSUE THREAD

**Issue by rochana-atapattu** [liamg/darktile#287]
**Describe the bug**
When I try to start an interactive ssh session with either golang.org/x/crypto/ssh 
```
session, err := proxyClient.NewSession()
if err != nil {
	log.Fatalln(err)
}
defer session.Close()

modes := ssh.TerminalModes{
		ssh.ECHO:          0,     // disable echoing
		ssh.TTY_OP_ISPEED: 14400, // input speed = 14.4kbaud
		ssh.TTY_OP_OSPEED: 14400, // output speed = 14.4kbaud
}

if err := session.RequestPty("xterm", 80, 40, modes); err != nil {
		session.Close()
		log.Fatalln(err)
}
session.Stdout = os.Stdout
session.Stderr = os.Stderr
session.Stdin = os.Stdin
if err = session.Shell(); err != nil {
		log.Fatalln(err)
}
session.Wait() 
```
or
 
```
exec.Command("ssh","ec2-user@host")
cmd.Stdout = os.Stdout
cmd.Stderr =os.Stderr
cmd.Stdin = os.Stdin
err = cmd.Run()
```
The connection is established but I can't type in anything or I don't get any output from the remote instance

**To Reproduce**
Create an interactive ssh session with go in windows

**Expected behavior**
An ssh session where user can interact with the remote instance

**Screenshots**
![output](https://user-images.githubusercontent.com/31321610/74634005-01282900-5189-11ea-9b6e-dd9306875c77.png)

**Environment (please complete the following information):**
 - Windows 10
 -  go1.13.7
 - cmd.exe

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
