### ISSUE TITLE
Colors don't look right

### ISSUE THREAD

**Issue by millerlogic** [liamg/darktile#292]
**Describe the bug**
Colors don't look right. I'm on Linux.

**To Reproduce**
1. ```msgcat --color=test```
2. Compare output with xfce4-terminal or other common terminal.

**Expected behavior**
Fairly smooth flow of colors in hue/saturation section.

**Screenshots**
![image](https://user-images.githubusercontent.com/6836420/106540744-2612ca80-64c6-11eb-8d73-11bf2885c092.png)

**Environment (please complete the following information):**
 - OS + Version: Debian GNU/Linux 10 (buster)
 - Go Version: 1.14.1
 - Shell: bash

**Additional context**
My computer is several years old and doesn't have a good graphics card, but it runs fine. I can't do high intensive graphics, though the colors usually look fine.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
