### ISSUE TITLE
Brew install on a new machine fails

### ISSUE THREAD

**Issue by euchch** [liamg/darktile#295]
**Describe the bug**
As per your docks, on a new machine having golang isntalled

> ➜ go version 
> go version go1.16.5 darwin/amd64

Running 
brew tap liamg/aminal
brew install aminal

Fails with the following error:
> go: cannot find main module, but found Gopkg.lock in /tmp/.gobuild/src/github.com/liamg/aminal

It seems like setup scripts are not setup correctly, it runs `./build.sh v0.8.7`

**To Reproduce**
1. Open terminal
2. Run `brew tap liamg/aminal`
3. Run `brew install aminal `

**Expected behavior**
Having animal terminal installed

**Environment (please complete the following information):**
 - OS + Version: [e.g. Ubuntu 18.04] - On Linux run `cat /etc/*release`
➜ uname -a
Darwin MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

 - Go Version [e.g. 1.10.1] - Run `go version`
➜ go version
go version go1.16.5 darwin/amd64
 - Shell [e.g. Bash/Zsh] - Run `echo $0`
➜ echo $0
-zsh

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
