### ISSUE TITLE
Support for different cursor shapes

### ISSUE THREAD

**Issue by pinpox** [liamg/darktile#303]
Currently on only the "block" cursor seems to be supported. When using vim, most terminals switch to the "i-beam" shape when in insert mode, it would be great if darktile could support different cursor shapes aswell and have this feature.

**Comment by liamg** [comment]
Good idea, I'll sort this next :+1:

**Comment by liamg** [comment]
I took it a step further and added support for images as cursors too :D

![cursor](https://user-images.githubusercontent.com/1187060/127916349-aee69d4a-07fa-4d5e-8a0a-9c3ada9b0c31.gif)

**Comment by pinpox** [comment]
:laughing:
